// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: delivery_forecast.proto

#ifndef PROTOBUF_delivery_5fforecast_2eproto__INCLUDED
#define PROTOBUF_delivery_5fforecast_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protobuf_delivery_5fforecast_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void InitDefaultsDeliveryForecastImpl();
void InitDefaultsDeliveryForecast();
inline void InitDefaults() {
  InitDefaultsDeliveryForecast();
}
}  // namespace protobuf_delivery_5fforecast_2eproto
namespace Sprout {
class DeliveryForecast;
class DeliveryForecastDefaultTypeInternal;
extern DeliveryForecastDefaultTypeInternal _DeliveryForecast_default_instance_;
}  // namespace Sprout
namespace Sprout {

// ===================================================================

class DeliveryForecast : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:Sprout.DeliveryForecast) */ {
 public:
  DeliveryForecast();
  virtual ~DeliveryForecast();

  DeliveryForecast(const DeliveryForecast& from);

  inline DeliveryForecast& operator=(const DeliveryForecast& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeliveryForecast(DeliveryForecast&& from) noexcept
    : DeliveryForecast() {
    *this = ::std::move(from);
  }

  inline DeliveryForecast& operator=(DeliveryForecast&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const DeliveryForecast& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeliveryForecast* internal_default_instance() {
    return reinterpret_cast<const DeliveryForecast*>(
               &_DeliveryForecast_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(DeliveryForecast* other);
  friend void swap(DeliveryForecast& a, DeliveryForecast& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeliveryForecast* New() const PROTOBUF_FINAL { return New(NULL); }

  DeliveryForecast* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const DeliveryForecast& from);
  void MergeFrom(const DeliveryForecast& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DeliveryForecast* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 counts = 3 [packed = true];
  int counts_size() const;
  void clear_counts();
  static const int kCountsFieldNumber = 3;
  ::google::protobuf::uint32 counts(int index) const;
  void set_counts(int index, ::google::protobuf::uint32 value);
  void add_counts(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      counts() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_counts();

  // uint64 received_or_lost_count = 1;
  void clear_received_or_lost_count();
  static const int kReceivedOrLostCountFieldNumber = 1;
  ::google::protobuf::uint64 received_or_lost_count() const;
  void set_received_or_lost_count(::google::protobuf::uint64 value);

  // uint64 time = 2;
  void clear_time();
  static const int kTimeFieldNumber = 2;
  ::google::protobuf::uint64 time() const;
  void set_time(::google::protobuf::uint64 value);

  // uint64 throwaway = 4;
  void clear_throwaway();
  static const int kThrowawayFieldNumber = 4;
  ::google::protobuf::uint64 throwaway() const;
  void set_throwaway(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Sprout.DeliveryForecast)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > counts_;
  mutable int _counts_cached_byte_size_;
  ::google::protobuf::uint64 received_or_lost_count_;
  ::google::protobuf::uint64 time_;
  ::google::protobuf::uint64 throwaway_;
  mutable int _cached_size_;
  friend struct ::protobuf_delivery_5fforecast_2eproto::TableStruct;
  friend void ::protobuf_delivery_5fforecast_2eproto::InitDefaultsDeliveryForecastImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DeliveryForecast

// uint64 received_or_lost_count = 1;
inline void DeliveryForecast::clear_received_or_lost_count() {
  received_or_lost_count_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 DeliveryForecast::received_or_lost_count() const {
  // @@protoc_insertion_point(field_get:Sprout.DeliveryForecast.received_or_lost_count)
  return received_or_lost_count_;
}
inline void DeliveryForecast::set_received_or_lost_count(::google::protobuf::uint64 value) {
  
  received_or_lost_count_ = value;
  // @@protoc_insertion_point(field_set:Sprout.DeliveryForecast.received_or_lost_count)
}

// uint64 time = 2;
inline void DeliveryForecast::clear_time() {
  time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 DeliveryForecast::time() const {
  // @@protoc_insertion_point(field_get:Sprout.DeliveryForecast.time)
  return time_;
}
inline void DeliveryForecast::set_time(::google::protobuf::uint64 value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:Sprout.DeliveryForecast.time)
}

// repeated uint32 counts = 3 [packed = true];
inline int DeliveryForecast::counts_size() const {
  return counts_.size();
}
inline void DeliveryForecast::clear_counts() {
  counts_.Clear();
}
inline ::google::protobuf::uint32 DeliveryForecast::counts(int index) const {
  // @@protoc_insertion_point(field_get:Sprout.DeliveryForecast.counts)
  return counts_.Get(index);
}
inline void DeliveryForecast::set_counts(int index, ::google::protobuf::uint32 value) {
  counts_.Set(index, value);
  // @@protoc_insertion_point(field_set:Sprout.DeliveryForecast.counts)
}
inline void DeliveryForecast::add_counts(::google::protobuf::uint32 value) {
  counts_.Add(value);
  // @@protoc_insertion_point(field_add:Sprout.DeliveryForecast.counts)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
DeliveryForecast::counts() const {
  // @@protoc_insertion_point(field_list:Sprout.DeliveryForecast.counts)
  return counts_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
DeliveryForecast::mutable_counts() {
  // @@protoc_insertion_point(field_mutable_list:Sprout.DeliveryForecast.counts)
  return &counts_;
}

// uint64 throwaway = 4;
inline void DeliveryForecast::clear_throwaway() {
  throwaway_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 DeliveryForecast::throwaway() const {
  // @@protoc_insertion_point(field_get:Sprout.DeliveryForecast.throwaway)
  return throwaway_;
}
inline void DeliveryForecast::set_throwaway(::google::protobuf::uint64 value) {
  
  throwaway_ = value;
  // @@protoc_insertion_point(field_set:Sprout.DeliveryForecast.throwaway)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Sprout

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_delivery_5fforecast_2eproto__INCLUDED
